#!/usr/bin/env bash
# Using if and elif to manage a file
contractor () {
	kill "$(pgrep -f /manage_my_process)"
	rm -f /var/run/my_process.pid &
}

if [[ "$1" == "start" ]]
then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [[ "$1" == "stop" ]]
then
	contractor; echo "manage_my_process stopped"
elif [[ "$1" == "restart" ]]
then
	contractor; ./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
